FROM python:3.12.11-slim

# Install dependencies
RUN apt update && apt install -y --no-install-recommends \
        libzbar0t64 \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir \
        opencv-python-headless \
        onnxruntime \
        requests \
        fastapi \
        uvicorn \
        loguru \
        boto3 \
        PyYAML \
        pycryptodome \
        pillow \
        pyclipper \
        shapely \
        tqdm \
        python-multipart \
        pyzbar \
    && tar -zcf /usr/local/lib/python3.12/sp.tar.gz -C /usr/local/lib/python3.12 site-packages \
    && rm -rf /usr/local/lib/python3.12/site-packages

# Copy and set up entrypoint
COPY decompress.sh /decompress.sh
RUN chmod +x /decompress.sh

# Set up entrypoint and command
ENTRYPOINT ["/decompress.sh"]
CMD ["bash"]
